/* tslint:disable */
import './404'
import './dashboard'
import './edit'
import './email'
import './fackbook'
import './home'
import './original-whatapp'
import './QQ'
import './search'
import './skype'
import './中文'
import './微信'
import './英文'
